version: '3.8'

services:
  db:
    image: postgres:15
    container_name: financeiro-db
    environment:
      POSTGRES_USER: financial_user
      POSTGRES_PASSWORD: ChangeMe123!
      POSTGRES_DB: financeiro_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
